name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://Tomyokesh33:${HF_TOKEN}@huggingface.co/spaces/Tomyokesh33/ai-agent-chatbot.git || true
          git push space main --force